# -*- coding: utf-8 -*-
"""
Created on Thu Apr 03 23:09:54 2014

@author: aaditya prakash
"""
import utilities

problem_number = '002'
problem_statement = """Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""


iterFib = utilities.Fibonacci()

def sum_even_fib(parameter):
    sum = 0
    while True:
        fib = iterFib.next()

        if fib > parameter :
            break
        elif fib % 2 == 0 :
            continue
        else:
            sum += fib
    return sum

print(sum_even_fib(4000000))

answer = '4613732'