# -*- coding: utf-8 -*-
"""
Created on Tue Apr 15 00:27:20 2014

@author: aaditya prakash
"""

import utilities
import math
import time

problem_number = '029'
problem_statement = """
How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
"""

def Distinct_Terms_a_pow_b(aLimit, bLimit):

    allTerms = set([a**b for a in xrange(2,aLimit+1) for b in xrange(2, bLimit+1)])    
    
    return len(allTerms)


timeStart = time.clock()
print(Distinct_Terms_a_pow_b(100,100))
print('Time (sec):' + str(time.clock() - timeStart))
answer = '9183'



